version: "3"

services:
    web:
        build:
            context: ../
            dockerfile: deploy/Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - db
        restart: always
        environment:
            FLASK_ENV: production
            POSTGRES_DB: flask_fullstack
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: db
            JWT_COOKIE_SECURE: True
            MODE: production

    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: flask_fullstack
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
