version: "3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            FLASK_APP: flaskr
            FLASK_ENV: production
            POSTGRES_DB: flask_fullstack
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: db

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: flask_fullstack
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
